Практика 2
mihpir/praktika_mmad pull request #2
Opened 2021-03-12 10:09 UTC by mihpir

2021-03-12 10:20 UTC, dm43r approved these changes
Замечаний нет

2021-03-17 11:50 UTC, dm43r commented on 02_pract/2.py
> +print('Задача 10:\t', minMax(10), '\n')
Укажи номер варианта в начале файла в виде комментария.

2021-03-17 12:09 UTC, dm43r requested changes

2021-03-17 12:09 UTC, dm43r commented on 02_pract/2.py
>  import random
Перенеси строчку c подключением random наверх.

2021-03-17 12:15 UTC, dm43r approved these changes

2021-03-20 06:41 UTC, stanislavlyalin requested changes

2021-03-20 06:41 UTC, stanislavlyalin commented on 02_pract/2.py
> +    return [abs(m1[i]-m2[i]) for i in range(len(m1))]
Необходима проверка, что длины массивов `m1` и `m2` совпадают. В противном случае выбрасывать исключение, а в вызывающем коде перехватывать это исключение

2021-03-22 17:40 UTC, merged