Практика 4
mihpir/praktika_mmad pull request #4
Opened 2021-03-12 10:11 UTC by mihpir

2021-03-12 10:21 UTC, dm43r approved these changes
Замечаний нет

2021-03-17 12:28 UTC, dm43r commented on 04_pract/kNN.py
> +
Поработай с оформлением программного кода. Убери лишние пустые строки.

2021-03-17 12:30 UTC, dm43r commented on 04_pract/run.py
> +print(monkeys[object_class])
При выводе результата классификации добавь строку "\nРезультат классификации: ".

2021-03-17 12:30 UTC, dm43r commented on 04_pract/run.py
> +1
Необходимо удалить данную строку

2021-03-25 17:46 UTC, stanislavlyalin requested changes

2021-03-25 17:46 UTC, stanislavlyalin commented on 04_pract/kNN.py
> +    for i in range(sub_X.shape[1]):
Если у функций `mean` и `std` задать параметр `axis`, то цикл будет не нужен, т.к. они вычислят результат по столбцам. В переменной `temp` тоже нет необходимости. Нужно сохранить средние по столбцам и среднеквадратические отклонения по столбцам, чтобы потом можно было нормализовать объект `obj`. Код должен выглядеть примерно так:
```python
means = sub_X.mean(axis=...)
stds = sub_X.std(axis=...)
sub_X = (sub_X - means) / stds
obj = (obj - means) / stds
```

2021-03-25 17:46 UTC, stanislavlyalin commented on 04_pract/kNN.py
> +def k_nearest(X, k, obj):
Реализуйте алгоритм `k_nearest` в виде класса `KNN` с методами `fit` и `predict`. Метод `fit` будет принимать обучающую выборку как матрицу признаков `X` (у вас это `sub_X`) и вектор классов `y` (у вас это последний столбец матрицы `X`), сохранять нормализованную выборку и параметры нормализации, а метод `predict` будет принимать объект, выполнять его нормализацию с сохранёнными ранее параметрами нормализации и выдавать класс объекта.

2021-03-28 12:35 UTC, merged