Практика 6
mihpir/praktika_mmad pull request #6
Opened 2021-03-12 10:13 UTC by mihpir

2021-03-12 10:23 UTC, dm43r approved these changes
Замечаний нет

2021-03-17 12:53 UTC, dm43r reviewed
Укажи номер варианта в начале файла в виде комментария.

2021-03-25 17:53 UTC, stanislavlyalin requested changes

2021-03-25 17:53 UTC, stanislavlyalin commented on 06_pract/test.py
> +#вариант №2
Картинки в репозитории хранить не нужно. Удалите их.

2021-03-25 17:53 UTC, stanislavlyalin commented on 06_pract/test.py
> +#вариант №2
Добавьте поясняющие комментарии к ключевым фрагментам кода

2021-03-25 17:53 UTC, stanislavlyalin commented on 06_pract/test.py
> +im.save('ready_5.jpg')
Имя сохраняемой картинки передавайте как аргумент командной строки. Проверяйте наличие аргумента, и если его нет, выводите на экран предупреждение

2021-03-28 12:39 UTC, merged