Практика 8
mihpir/praktika_mmad pull request #8
Opened 2021-03-12 10:16 UTC by mihpir

2021-03-12 10:24 UTC, dm43r approved these changes
Замечаний нет

2021-03-17 13:02 UTC, dm43r reviewed
Михаил, укажите номер варианта в начале файла в виде комментария!

2021-03-25 18:58 UTC, stanislavlyalin requested changes

2021-03-25 18:58 UTC, stanislavlyalin commented on 08_pract/regexp.py
> +reg = r'^[\w\-.]+@[A-Za-z0-9][\w\-]*.[\w\-.]+$'
К каждому регулярному выражению добавьте комментарий с пояснением работы, например
```python
# в начале строки должны встречаться буквы, дефисы и точки 1 и более раз
# затем должен быть символ @
# затем буква в любом регистре или цифра
# затем ...
reg = r'^[\w\-.]+@[A-Za-z0-9][\w\-]*.[\w\-.]+$'
```

2021-03-25 18:58 UTC, stanislavlyalin commented on 08_pract/regexp.py
> +reg = r'^[\w\-.]+@[A-Za-z0-9][\w\-]*.[\w\-.]+$'
Регулярное выражение не совсем корректное. До знака `@` могут быть и точки `.`, и подчёркивания `_`. После знака `@` тот же набор может встречаться 1 или более раз. Затем обязательно точка и последовательность букв в любом регистре.

2021-03-28 12:42 UTC, merged